<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="FB_Soldering" Id="{7c5b309b-ddd2-4dc2-9501-bbf31ea7886e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_Soldering EXTENDS FB_Sequence
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^.Main();

CASE m_SequenceNumber OF
	SequenceStartNamesStart:
	
END_CASE
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>