<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="FB_Sequence" Id="{fb4892fb-69c3-469d-b6eb-dfd06ca281dc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Sequence
VAR_INPUT
END_VAR
VAR_OUTPUT
	OutSequnceState:EN_SequenceState;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>